<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '1f45ee513dc8b4465cf85aa962dee441' => $vendorDir . '/talesoft/phim/src/Phim/functions.php',
);
