<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf093c1ee0ab8c20d3d259869f09244d4
{
    public static $files = array (
        '1f45ee513dc8b4465cf85aa962dee441' => __DIR__ . '/..' . '/talesoft/phim/src/Phim/functions.php',
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/..' . '/talesoft/phim/src',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->fallbackDirsPsr4 = ComposerStaticInitf093c1ee0ab8c20d3d259869f09244d4::$fallbackDirsPsr4;

        }, null, ClassLoader::class);
    }
}
